# Generated by Django 5.2.8 on 2025-12-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=True)),
                ('bilish', models.FloatField(default=0)),
                ('bilish_count', models.IntegerField(default=0)),
                ('qollash', models.FloatField(default=0)),
                ('qollash_count', models.FloatField(default=0)),
                ('muhokama', models.FloatField(default=0)),
                ('muhokama_count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.testcase', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
            },
        ),
    ]
