# Generated by Django 5.2.8 on 2025-11-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_score_score'),
        ('tests', '0003_test_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testcase', unique=True, verbose_name='Test'),
        ),
    ]
