# Generated by Django 5.2.8 on 2025-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_alter_score_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='bilish',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='bilish_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='muhokama',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='muhokama_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='qollash',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='qollash_count',
            field=models.FloatField(default=0),
        ),
    ]
