# Generated by Django 5.2.8 on 2025-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_score_bilish_score_bilish_count_score_muhokama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
