# Generated by Django 5.2.8 on 2025-11-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_score_completed_score_total'),
        ('tests', '0006_ball_alter_test_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.testcase', verbose_name='Test'),
        ),
    ]
