# Generated by Django 5.2.8 on 2025-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_class_name'),
        ('scores', '0002_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scores',
            field=models.ManyToManyField(blank=True, null=True, to='scores.score', verbose_name='Natijalari'),
        ),
    ]
