# Generated by Django 5.2.8 on 2025-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_scores'),
        ('scores', '0004_alter_score_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scores',
            field=models.ManyToManyField(blank=True, to='scores.score', verbose_name='Natijalari'),
        ),
    ]
