# Generated by Django 5.2.8 on 2025-11-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'TestCase',
                'verbose_name_plural': 'TestCaselar',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer_a', models.CharField(max_length=1024, verbose_name='A variant')),
                ('answer_b', models.CharField(max_length=1024, verbose_name='B variant')),
                ('answer_c', models.CharField(max_length=1024, verbose_name='C variant')),
                ('answer_d', models.CharField(max_length=1024, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="Tog'ri javob")),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testcase', verbose_name='Testcase')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
    ]
