# Generated by Django 5.2.8 on 2025-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_score',
            field=models.FloatField(default=0, verbose_name='Savol bali'),
        ),
    ]
