# Generated by Django 5.2.8 on 2025-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tests_count',
            field=models.IntegerField(default=0),
        ),
    ]
