# Generated by Django 5.2.8 on 2025-11-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testcase_tests_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='tests_count',
        ),
    ]
