# Generated by Django 5.2.8 on 2025-11-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_testcase_tests_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Mezon nomi')),
                ('score', models.FloatField(verbose_name='Savol bali')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.ball', verbose_name='Test bali'),
        ),
    ]
